export default {
  destinations: [
    {
      name: 'Nice France',
      slug: 'nice',
      img: 'nice_1.jpg',
      description:
        'Nice, a jewel of the French Riviera, offers serene beauty and big-city energy. The Promenade des Anglais - ideal for catching a sunset - offers coastal calm. Main thoroughfares such as Massena Square, Place Garibaldi and Albert I Garden are ideal meeting spots that come alive during public events.',
      images: [
        { src: 'nice_2.jpg', orientation: 'vertical' },
        { src: 'nice_3.jpg', orientation: 'vertical' },
        { src: 'nice_4.jpg', orientation: 'vertical' },
        { src: 'nice_5.jpg', orientation: 'vertical' },
        { src: 'nice_6.jpg', orientation: 'vertical' },
        { src: 'nice_7.jpg', orientation: 'vertical' },
        { src: 'nice_8.jpg', orientation: 'vertical' },
        { src: 'nice_9.jpg', orientation: 'vertical' },
        { src: 'nice_10.jpg', orientation: 'vertical' },
        { src: 'nice_11.jpg', orientation: 'horizontal' },
      ],
    },
    {
      name: 'Monte Carlo',
      slug: 'monte-carlo',
      img: 'monteCarlo_1.jpg',
      description:
        'Monte Carlo is a tiny district of Monaco, but attracts plenty with its stunning sea views, world-class shopping, gourmet dining, and exciting nightlife. Monte-Carlo Casino attracts those looking to test their luck at its opulent gambling rooms, while the Monaco Opera House regularly hosts international performances.',
      images: [
        { src: 'monteCarlo_2.jpg', orientation: 'horizontal' },
        { src: 'monteCarlo_3.jpg', orientation: 'horizontal' },
        { src: 'monteCarlo_4.jpg', orientation: 'horizontal' },
        { src: 'monteCarlo_5.jpg', orientation: 'horizontal' },
      ],
    },
    {
      name: 'Ljoret de Mar',
      slug: 'ljoret-de-mar',
      img: 'ljoret_1.jpg',
      description:
        'Lloret de Mar is a small Catalan tourist town on the Mediterranean coast. It is located in the province of Girona. Nearby are the cities of Blanes and Tossa de Mar and it is relatively close to Barcelona. At the beginning of the nineties, it attracted many tourists and now represents an important part of Costa Brava.',
      images: [
        { src: 'ljoret_2.jpg', orientation: 'horizontal' },
        { src: 'ljoret_3.jpg', orientation: 'horizontal' },
        { src: 'ljoret_4.jpg', orientation: 'horizontal' },
        { src: 'ljoret_5.jpg', orientation: 'horizontal' },
        { src: 'ljoret_6.jpg', orientation: 'horizontal' },
        { src: 'ljoret_7.jpg', orientation: 'horizontal' },
      ],
    },
    {
      name: 'Barselona',
      slug: 'barselona',
      img: 'barselona_1.jpg',
      description:
        'Barcelona is the capital of Catalonia, one of the main European economic centers, with one of the main Mediterranean ports and the airport in Barcelona is the second largest in Spain. It is located on the shores of the Mediterranean, very rich cultural and historical heritage, ex. architectural works of Antonio Gaudí.',
      images: [
        { src: 'nice_2.jpg', orientation: 'vertical' },
        { src: 'nice_3.jpg', orientation: 'vertical' },
        { src: 'nice_4.jpg', orientation: 'vertical' },
        { src: 'nice_5.jpg', orientation: 'vertical' },
        { src: 'nice_6.jpg', orientation: 'vertical' },
        { src: 'nice_7.jpg', orientation: 'vertical' },
        { src: 'nice_8.jpg', orientation: 'vertical' },
        { src: 'nice_9.jpg', orientation: 'vertical' },
        { src: 'nice_10.jpg', orientation: 'vertical' },
        { src: 'nice_11.jpg', orientation: 'horizontal' },
      ],
    },
    {
      name: 'Park Guell',
      slug: 'park-guell',
      img: 'guell_1.jpg',
      description:
        'The park was originally part of a commercially unsuccessful residential area - the idea of Count Eusebio de Guelj. It was inspired by British parks and therefore got the English name park. It was later turned into a city garden. The park project was created by the architect Gaudí in his distinctive style.',
      images: [
        { src: 'nice_2.jpg', orientation: 'vertical' },
        { src: 'nice_3.jpg', orientation: 'vertical' },
        { src: 'nice_4.jpg', orientation: 'vertical' },
        { src: 'nice_5.jpg', orientation: 'vertical' },
        { src: 'nice_6.jpg', orientation: 'vertical' },
        { src: 'nice_7.jpg', orientation: 'vertical' },
        { src: 'nice_8.jpg', orientation: 'vertical' },
        { src: 'nice_9.jpg', orientation: 'vertical' },
        { src: 'nice_10.jpg', orientation: 'vertical' },
        { src: 'nice_11.jpg', orientation: 'horizontal' },
      ],
    },
    {
      name: 'Figueres',
      slug: 'figueres',
      img: 'figueres_1.jpg',
      description:
        'Figueras or Figueres is a city in Spain located in the province of Girona, in the autonomous community of Catalonia. The city lies in the tourist region of Costa Brava. Figueres is home to the Salvador Dali Museum, as it is his birthplace.',
      images: [
        { src: 'nice_2.jpg', orientation: 'vertical' },
        { src: 'nice_3.jpg', orientation: 'vertical' },
        { src: 'nice_4.jpg', orientation: 'vertical' },
        { src: 'nice_5.jpg', orientation: 'vertical' },
        { src: 'nice_6.jpg', orientation: 'vertical' },
        { src: 'nice_7.jpg', orientation: 'vertical' },
        { src: 'nice_8.jpg', orientation: 'vertical' },
        { src: 'nice_9.jpg', orientation: 'vertical' },
        { src: 'nice_10.jpg', orientation: 'vertical' },
        { src: 'nice_11.jpg', orientation: 'horizontal' },
      ],
    },
    {
      name: 'Menton France',
      slug: 'menton',
      img: 'menton_1.jpg',
      description:
        'Menton has always been a border town. For centuries it formed the border between Provence and Genoa. With the referendum of 1860, the city became French and has remained so until today.',
      images: [
        { src: 'menton_2.jpg', orientation: 'horizontal' },
        { src: 'menton_3.jpg', orientation: 'vertical' },
        { src: 'menton_4.jpg', orientation: 'vertical' },
        { src: 'menton_5.jpg', orientation: 'horizontal' },
        { src: 'menton_6.jpg', orientation: 'horizontal' },
        { src: 'menton_7.jpg', orientation: 'vertical' },
        { src: 'menton_8.jpg', orientation: 'horizontal' },
        { src: 'menton_9.jpg', orientation: 'vertical' },
        { src: 'menton_10.jpg', orientation: 'vertical' },
        { src: 'menton_11.jpg', orientation: 'horizontal' },
        { src: 'menton_12.jpg', orientation: 'vertical' },
        { src: 'menton_13.jpg', orientation: 'horizontal' },
        { src: 'menton_14.jpg', orientation: 'vertical' },
        { src: 'menton_15.jpg', orientation: 'vertical' },
        { src: 'menton_16.jpg', orientation: 'horizontal' },
        { src: 'menton_17.jpg', orientation: 'horizontal' },
        { src: 'menton_18.jpg', orientation: 'vertical' },
        { src: 'menton_19.jpg', orientation: 'horizontal' },
        { src: 'menton_20.jpg', orientation: 'vertical' },
        { src: 'menton_21.jpg', orientation: 'horizontal' },
      ],
    },
    {
      name: 'Pisa Italy',
      slug: 'pisa',
      img: 'pisa_1.jpg',
      description:
        'Pisa is a city in central Italy. Pisa is the largest city and the center of the Pisa district of the same name within the Italian province of Tuscany. Pisa is world famous for the Leaning Tower of Pisa, the most famous curved building in the world.',
      images: [
        { src: 'pisa_2.jpg', orientation: 'horizontal' },
        { src: 'pisa_3.jpg', orientation: 'horizontal' },
        { src: 'pisa_4.jpg', orientation: 'horizontal' },
        { src: 'pisa_5.jpg', orientation: 'vertical' },
        { src: 'pisa_6.jpg', orientation: 'vertical' },
        { src: 'pisa_7.jpg', orientation: 'horizontal' },
        { src: 'pisa_8.jpg', orientation: 'horizontal' },
        { src: 'pisa_9.jpg', orientation: 'horizontal' },
        { src: 'pisa_10.jpg', orientation: 'horizontal' },
        { src: 'pisa_11.jpg', orientation: 'vertical' },
        { src: 'pisa_12.jpg', orientation: 'vertical' },
        { src: 'pisa_13.jpg', orientation: 'horizontal' },
        { src: 'pisa_14.jpg', orientation: 'horizontal' },
      ],
    },
  ],
};
